default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

# SQLite3 configuration
sqlite3: &sqlite3
  <<: *default
  adapter: sqlite3

# PostgreSQL configuration
postgres: &postgres
  <<: *default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch('DATABASE_USERNAME', 'postgres') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD', 'postgres') %>
  host: <%= ENV.fetch('DATABASE_HOST','localhost') %>

development:
  <<: *postgres
  database: <%= "#{ENV.fetch('APP_NAME', 'anubis_backend_engine')}_development" %>

test:
  <<: *postgres
  database: <%= "#{ENV.fetch('APP_NAME', 'anubis_backend_engine')}_test" %>

production:
  primary:
    <<: *postgres
    database: storage/production.sqlite3
  cache:
    <<: *sqlite3
    database: storage/production_cache.sqlite3
    migrations_paths: db/cache_migrate
  queue:
    <<: *sqlite3
    database: storage/production_queue.sqlite3
    migrations_paths: db/queue_migrate
  cable:
    <<: *sqlite3
    database: storage/production_cable.sqlite3
    migrations_paths: db/cable_migrate
